import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { SimpleTable } from './components/Table/simple-table'
import advancedFormat from "dayjs/plugin/advancedFormat";
import djs from "dayjs";
import { randEmail, randFullName, randPastDate, randPhoneNumber } from "@ngneat/falso";

const inter = Inter({ subsets: ['latin'] })

djs.extend(advancedFormat);

// Generate mock data for our table
const data = Array(20)
  .fill(1)
  .map(() => {
    const date = randPastDate();
    return {
      name: randFullName(),
      contact: {
        email: randEmail(),
        phone: randPhoneNumber()
      },
      dob: {
        year: date.getFullYear(),
        month: date.getMonth(),
        day: date.getDate()
      }
    };
  });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div style={{ height:'100%', width: '100%'}}>
          <SimpleTable
            data={data}
            useCards
            dataKeyFn={item => item?.name || "empty"}
            cols={[
              ["name", "Name", "name"],
              ["email", "Email", "contact.email"],
              ["phone", "Phone", "contact.phone"],
              [
                "dob",
                <i>Date Of Birth</i>,
                item =>
                  djs(`${item.dob.year}-${item.dob.month}-${item.dob.day}`).format(
                    "Do MMMM YYYY"
                  )
              ]
            ]}
          />
        </div>
      </main>
    </>
  )
}
